#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build --build-arg BRANCH=`git rev-parse --abbrev-ref HEAD` \
             --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg COMMIT_AUTHOR=`git log -1 --pretty=format:'%an'` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg VCS_URL=`git config --get remote.origin.url | sed -e 's/git@github.com:/https:\/\/github.com\//'` \
             -t $IMAGE_NAME .
