#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
BRANCH=`git rev-parse --abbrev-ref HEAD`
BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
COMMIT_AUTHOR=`git log -1 --pretty=format:'%ae'`
VCS_REF=`git rev-parse --short HEAD`
VCS_URL=`git config --get remote.origin.url | sed -e 's/git@github.com:/https:\/\/github.com\//'`
echo $BRANCH
echo $BUILD_DATE
echo $COMMIT_AUTHOR
echo $VCS_REF
echo $VCS_URL
docker build --build-arg BRANCH \
             --build-arg BUILD_DATE \
             --build-arg COMMIT_AUTHOR \
             --build-arg VCS_REF \
             --build-arg VCS_URL \
             -t $IMAGE_NAME .
