#!/usr/bin/with-contenv sh

user=cloudplow
if [ -n $PUID ] && [ $PUID == 0]
then
    user=root
fi
if [ ! -f ${CLOUDPLOW_CONFIG} ]
then
    exec s6-setuidgid $user python3 /opt/cloudplow/cloudplow.py run
    echo "Default config.json generated, please configure for your environment. Exiting."
elif grep -qP "\"rclone_config_path\":\s*\"/home/(seed|user)/\.config/rclone/rclone\.conf\"" ${CLOUDPLOW_CONFIG}
then
    echo "config.json has not been configured, exiting."
    echo "Along with configuring other settings, rclone_config_path needs to point to your rclone.conf file, expected to be mapped into this container under /rclone_config/."
elif grep -qP "\"rclone_config_path\":\s*\"/rclone_config/.*\.conf\"" ${CLOUDPLOW_CONFIG}
then
    exec s6-setuidgid $user python3 /opt/cloudplow/cloudplow.py run
fi

