name: Test PR - Build image
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build_pr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [linux-arm-v7, linux-arm64, linux-amd64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver-opts: image=moby/buildkit:v0.10.6

      - name: Build images using buildx
        run: ARCHITECTURE=${{ matrix.architecture }} .github/workflows/docker_build_pr.sh
