#!/usr/bin/with-contenv sh

id cloudplow 2> /dev/null > /dev/null
cloudplow_exists=$?
if [ -n $PUID ] && [ $PUID == 0 ]
then
    if [ cloudplow_exists == 0 ]
    then
        userdel cloudplow
    fi
    exit
fi

if [ cloudplow_exists != 0 ]
then
    useradd -U -r -m -s /bin/false cloudplow
fi

if [ -n $PUID ] && [ $PUID != $(id -u cloudplow) ] && [ $PUID != 0 ]
then
    usermod -o -u "$PUID" cloudplow
    update="true"
fi

if [ -n $PGID ] && [ $PGID != $(id -g cloudplow) ] && [ $PGID != 0 ]
then
    groupmod -o -g "$PGID" cloudplow
    update="true"
fi

if [ -n $update ]
then
    echo "GID/UID
    User uid:    $(id -u cloudplow)
    User gid:    $(id -g cloudplow)
    ------------------------------------
    "

    chown -R cloudplow:cloudplow /config
    chown -R cloudplow:cloudplow /opt/cloudplow
fi
