#!/usr/bin/with-contenv sh

if [ -n $PUID ] && [ $PUID == 0 ] && [ id cloudplow ]
then
    userdel cloudplow
    groupdel cloudplow
    exit
fi

if [ -n $PUID ] && [ $PUID != $(id -u cloudplow) ] && [ $PUID != 0 ]
then
    usermod -o -u "$PUID" cloudplow
    update="true"
fi

if [ -n $PGID ] && [ $PGID != $(id -g cloudplow) ] && [ $PGID != 0 ]
then
    groupmod -o -g "$PGID" cloudplow
    update="true"
fi

echo "GID/UID
User uid:    $(id -u cloudplow)
User gid:    $(id -g cloudplow)
------------------------------------
"

if [ -n $update ]
then
    chown -R cloudplow:cloudplow /config
    chown -R cloudplow:cloudplow /opt/cloudplow
fi
