#!/command/with-contenv sh

uid=${PUID:-1000}
user=$(getent passwd $uid | awk -F: '{print $1}')
cd /opt/cloudplow
exec s6-setuidgid $user git pull
exec s6-setuidgid $user python3 -m pip install --no-cache-dir --upgrade -r requirements.txt
